#!/usr/bin/env python3
"""
Next.js Project Generator

This script helps generate a basic Next.js project structure.
"""

import os
import argparse
from pathlib import Path


def create_nextjs_project(project_name):
    """Create a basic Next.js project structure."""
    project_path = Path(project_name)

    if project_path.exists():
        print(f"Error: Directory {project_name} already exists!")
        return

    # Create project directory
    project_path.mkdir(parents=True, exist_ok=True)

    # Create directory structure
    dirs = [
        project_path / "src",
        project_path / "src" / "app",
        project_path / "src" / "components",
        project_path / "src" / "lib",
        project_path / "src" / "hooks",
        project_path / "src" / "types",
        project_path / "public",
    ]

    for directory in dirs:
        directory.mkdir(parents=True, exist_ok=True)

    # Create app directory structure
    app_dirs = [
        project_path / "src" / "app" / "api",
        project_path / "src" / "app" / "dashboard",
        project_path / "src" / "app" / "profile",
        project_path / "src" / "app" / "login",
        project_path / "src" / "app" / "register",
    ]

    for directory in app_dirs:
        directory.mkdir(parents=True, exist_ok=True)

    # Create basic layout.tsx
    layout_content = '''import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
'''
    (project_path / "src" / "app" / "layout.tsx").write_text(layout_content)

    # Create basic page.tsx
    page_content = '''export default function HomePage() {
  return (
    <main>
      <h1>Hello, Next.js!</h1>
    </main>
  )
}
'''
    (project_path / "src" / "app" / "page.tsx").write_text(page_content)

    # Create global CSS
    css_content = '''@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
'''
    (project_path / "src" / "app" / "globals.css").write_text(css_content)

    # Create package.json
    package_json_content = '''{
  "name": "my-nextjs-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.0.1"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10",
    "postcss": "^8",
    "tailwindcss": "^3",
    "eslint": "^8",
    "eslint-config-next": "14.0.1"
  }
}
'''
    (project_path / "package.json").write_text(package_json_content)

    # Create next.config.js
    next_config_content = '''/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
}

module.exports = nextConfig
'''
    (project_path / "next.config.js").write_text(next_config_content)

    # Create tsconfig.json
    tsconfig_content = '''{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "es6"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
'''
    (project_path / "tsconfig.json").write_text(tsconfig_content)

    # Create tailwind.config.js
    tailwind_config_content = '''/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
'''
    (project_path / "tailwind.config.js").write_text(tailwind_config_content)

    # Create .gitignore
    gitignore_content = '''# Dependencies
node_modules/

# Environment variables
.env*.local
.env*.dev
.env*.prod

# Next.js
.next/
out/

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
'''
    (project_path / ".gitignore").write_text(gitignore_content)

    # Create README.md
    readme_content = f'''# {project_name}

A Next.js project generated with Next.js Project Generator.

## Setup

1. Install dependencies:
   ```bash
   npm install
   ```

2. Run the development server:
   ```bash
   npm run dev
   ```

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Project Structure

```
{project_name}/
├── src/
│   ├── app/              # App Router pages
│   │   ├── layout.tsx    # Root layout
│   │   ├── page.tsx      # Home page
│   │   ├── globals.css   # Global styles
│   │   └── ...           # Other pages
│   ├── components/       # Reusable React components
│   ├── lib/              # Utility functions
│   ├── hooks/            # Custom hooks
│   └── types/            # TypeScript types
├── public/               # Static assets
├── package.json
├── next.config.js
├── tsconfig.json
├── tailwind.config.js
└── .gitignore
```
'''
    (project_path / "README.md").write_text(readme_content)

    print(f"✅ Next.js project '{project_name}' has been created successfully!")
    print(f"📁 Project structure:")
    print(f"   {project_name}/")
    print(f"   ├── src/")
    print(f"   │   ├── app/")
    print(f"   │   │   ├── layout.tsx")
    print(f"   │   │   ├── page.tsx")
    print(f"   │   │   └── globals.css")
    print(f"   │   ├── components/")
    print(f"   │   ├── lib/")
    print(f"   │   ├── hooks/")
    print(f"   │   └── types/")
    print(f"   ├── public/")
    print(f"   ├── package.json")
    print(f"   ├── next.config.js")
    print(f"   ├── tsconfig.json")
    print(f"   ├── tailwind.config.js")
    print(f"   └── README.md")


def main():
    parser = argparse.ArgumentParser(description="Next.js Project Generator")
    parser.add_argument("project_name", help="Name of the Next.js project to create")

    args = parser.parse_args()

    create_nextjs_project(args.project_name)


if __name__ == "__main__":
    main()